apiVersion: v1
kind: Pod
metadata:
   name: app-$env
   labels:
     name: app-$env
spec:
   containers:
   - name : app-$env
     image: $img
     ports:
     - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-$env
spec:
  selector:
    name: app-$env
  ports:
    - port: 5000
  type: LoadBalancer